### ISSUE TITLE
django.db.utils.OperationalError: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by skeips** [feldroy/django-crash-starter#72]
## What happened before?
Installed the dependencies as described in 18.6

pip install -r requirements/local.txt

then I ran migrate
## What happens now?
now the error occurs
psycopg2.OperationalError: fe_sendauth: no password supplied

## Steps to reproduce

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Project generation options)
[//]: # (* Logs)

**Comment by pydanny** [comment]
Are you on Windows?

**Comment by aaron-kaijser** [comment]
I have the same issue. Chapter 18 when I run the migrate command I get a bunch of errors.

`Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\core\management\commands\migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\migrations\loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\migrations\recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\migrations\recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\backends\base\base.py", line 260, in cursor
    return self._cursor()
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\backends\base\base.py", line 236, in _cursor
    self.ensure_connection()
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\backends\base\base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\django\db\backends\postgresql\base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\Arie\Anaconda3\envs\everycheese2\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: fe_sendauth: no password supplied`

I am on Windows 10. Followed all the steps in the book. This is such a pity because this doesn't allow me to run my server.

**Comment by iamaryanshandilya** [comment]
> Are you on Windows?

Yes I am also facing the same issue and I am using windows 10, can you please help me.
